### PR TITLE
fixes for htmlmin:ignore and ignoreCustomFragments

### LINKED ISSUE #464: ignoreCustomFragments over CLI
Is there a CLI-equivalent option for ignoreCustomFragments when calling html-minifier over command line?  Thanks for your help.

### PR DESCRIPTION
**Pull request by alexlamsl**
#436 is fixed by taking adjacent whitespaces of custom fragments into account
#442 is caused by order of operation for `htmlmin:ignore` and `ignoreCustomFragments`

Also fixed #464 while I'm at it :stuck_out_tongue_closed_eyes:

### CODE REVIEW

**Comment by alexlamsl** [comment]
Oops - slipped in `new Date()` --> `Date.now()` as VS Code was bugging me about it.

It is a [well supported feature](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date/now), but if you feel strongly about it I can back it out from the commit...

**Comment by alexlamsl** [comment]
`remove-empty-elements` was checked when "safe" options are selected on the web interface, and that made life rather difficult when doing quick tests

File: dist/htmlminifier.js [hunk 1]
```diff
@@ -1162,6 +1162,14 @@
     return text;
   }
 
+  function uniqueId(value) {
```
Comment (kangax) [inline dist/htmlminifier.js:1165]: What is this for?

File: dist/htmlminifier.js [hunk 2]
```diff
@@ -1178,37 +1186,37 @@
         stackNoTrimWhitespace = [],
         stackNoCollapseWhitespace = [],
         lint = options.lint,
-        t = new Date(),
+        t = Date.now(),
```
Comment (kangax) [inline dist/htmlminifier.js:1189]: Yeah, that's cool. I'm ok with it.

File: dist/htmlminifier.js (hunk 1 above)
Comment (alexlamsl) [inline dist/htmlminifier.js:1165]: 1. replaces `'htmlmin' + (Math.random() + '').slice(2)`, ensure that the identifier generated would not collide with input
   - the loop will almost never be executed more than once
2. replaces `<!-- htmlmin:temp -->` to avoid potential collision with input

Comment (alexlamsl) [inline dist/htmlminifier.js:1165]: By replacing `<!-- htmlmin:temp -->` with `<!--!deadb33f-->`, we also get to simplify `isIgnoredComment()` would may give a minor performance boost.

Also, this PR avoids any extra work done when `ignoreCustomFragments` or `<!-- htmlmin:temp -->` are not specified in the input, i.e. `uniqueId()` and `String.prototype.replace()` would never be called if none of this features are requested by the input.

Comment (kangax) [inline dist/htmlminifier.js:1165]: Hm, I thought it'd be pretty unlikely that random number would collide with user input. But I guess this doesn't hurt and is not in any frequently-executed code.

**Comment by kangax** [comment]
@alexlamsl thanks for all these awesome fixes and improvements lately! much appreciated :)
